/**
 * The extraction prompt, encoding the report-parsing rules from
 * kaiser_BUILD_SPEC.md directly — this is the one place those rules
 * actually get enforced at parse time, so keep it in sync with that doc.
 */
export function buildExtractionPrompt(threadText: string, todayIso: string): string {
  return `You are extracting structured data from a youth/adult pickup soccer league report email thread called "Kaiser". Today's date is ${todayIso} — use this only for inferring a missing year (rule 12), nothing else. Follow these rules exactly:

1. Read the ENTIRE thread below, not just the first message. Replies routinely correct the original report (a wrong scorer, a wrong assist, an own-goal miscredit). A correction stated in a reply SUPERSEDES the original message's claim for that specific fact.
2. Goals: extract every goal with its scorer. For the assist, either the literal word "assist" being used, OR a clear narrative pass-then-goal sequence naming both players (e.g. "Elan found Nicholas who put it through" — Elan assisted Nicholas; "X played in Y who scored" — X assisted Y) counts as stating an assist — this is reading what the sentence says, not guessing. If the text only names a scorer with no such stated or clearly narrated setup, leave assistRaw null rather than inventing one. An OWN GOAL (a player accidentally puts the ball in their own team's net — "auto goal," "own net," "into his own net," etc.) is NEVER credited to the player who put it in — standard convention here is the goal instead credits the LAST OPPOSING-TEAM player whose action put the ball in play just before it went in (e.g., the player whose corner, cross, or shot deflected in off a defender or wrong-footed a goalkeeper), never as an assist, as a plain unassisted goal for that opposing player, on the team that benefits. If the text doesn't identify a specific opposing player's touch as the proximate cause (truly no one but the own-goal-scorer is named in that passage), leave it out of goals[] entirely rather than crediting the own-goal-scorer or guessing a name.
3. MVP: mvpRaw is only ever an ADVISORY narrative signal — the actual MVP decision is a deterministic stats calculation done later in code (goals + assists, see computeMvp() in src/lib/stats-engine/goal-summary.ts), not yours to decide outright. Just report whoever the ORIGINAL report message's own narrative specifically calls out with standout qualitative language (e.g. "was the deciding factor," "unbelievable in net," "made many good stops and preserved our lead," "their most dangerous player all game") — this is only ever used as a tiebreaker between statistically-tied players, or as a fallback on the rare game with no extracted goals/assists at all. Other participants' opinions stated in REPLIES (e.g. "that was an MVP performance by X") are never a source. If no one is specifically called out, leave mvpRaw null — that's a normal, expected answer, not a failure to find one. On a scoreless or very low-scoring game specifically, there is no goals/assists stat to fall back on, so read more actively for the single best defensive/goalkeeping contribution named (a specific key save, block, or clearance credited to one player at a clearly dangerous moment) — a plain factual mention like "X made a save" on a described breakaway or one-on-one chance is enough signal in THIS situation, without needing the exceptional superlative language rule 3 otherwise requires. Still leave mvpRaw null if the text names no specific defensive moment at all.
4. Team rosters: these reports commonly open with a plain list of everyone who played, split into two clearly delimited groups presented in sequence — e.g. two blocks of comma-separated names separated by a blank line, sometimes under a header like "N people." When you see this structure, it IS a clear statement of both rosters (reading a list, not guessing a split): the FIRST group listed is the home roster, the SECOND group listed is the away roster. Only if the report has no such clearly delimited two-group listing at all (e.g. only a narrative paragraph naming a few players in passing) should you leave homeRosterRaw/awayRosterRaw as empty arrays rather than guessing a split. A roster entry sometimes has a parenthetical aside after the name (age, position, an editorial comment, e.g. "Ari (15 year old, he replaced Bex...)" or "Lesha (in goal)") — extract ONLY the actual name and drop the parenthetical entirely (-> "Ari", "Lesha"); it is never part of the name itself, even if it's long or descriptive.
5. Team labels: "home"/"away" is purely an internal bookkeeping distinction for this pickup league — it has no real meaning (no fixed home field). Only extract homeTeamLabelRaw/awayTeamLabelRaw if the report itself explicitly names each side (e.g. "Team Orange", "Team Blue," or similar) — same first-group/second-group convention as team rosters (rule 4): whichever side is named first is homeTeamLabelRaw. If the report never names the sides at all, leave both null rather than inventing a label.
6. Notable mentions: capture any standout narrative language about a specific player's performance (e.g. "X was dominant on both ends" or "Y went through 4-5 players"), even for a player who didn't score — this is exactly the kind of qualitative signal that a pure goal-count would miss. Quote the relevant snippet verbatim. When one sentence credits TWO OR MORE players jointly (e.g. "Russell and Emre totally controlled the middle of the field"), emit a SEPARATE notableMentions entry per player named, each with the same quote — playerRaw must always be exactly one person's name, never "X and Y" combined into one string.
7. Use the raw name exactly as written in the text (e.g. "Sasha SI", not a normalized or guessed full name). Do not attempt to resolve who a name "really" refers to — that happens in a separate step.
8. If the final score isn't clearly stated, leave homeScore/awayScore null rather than guessing.
9. If you are not confident about a field, leave it null / empty rather than guessing. It is always better to leave something out than to state something uncertain as fact.
10. Draft order: within each team's roster from rule 4's "N people" blank-line-separated listing, the first-listed player is that team's captain (the one who did the picking), and the rest of that team's list is already in the order they were drafted — this needs no separate extraction downstream (confirmed league convention for THAT listing format specifically; a report that instead names both sides up front, e.g. "Team Orange:"/"Team Blue:", is just listing who played, not draft order — see rule 5). Separately, a report sometimes ALSO narrates, in prose, the exact pick-by-pick order the two captains alternated in (e.g. "Vadim and Alik are captains, Nick Brazil selected first, then it was Alan, then Josh, then it was Emre and Matthew, then it was Oleg"). When you see this kind of explicit picked-in-this-order narrative — naming each captain's picks in sequence, not just who played — extract pickOrderRaw as an ordered array reflecting that exact sequence: each entry is a single name (one pick that turn), or an array of names when the text explicitly says multiple were picked together in the same turn (e.g. "then it was Emre and Matthew" -> ["Emre", "Matthew"]). Never include the two captains themselves in this list. If the report doesn't narrate an explicit pick order like this, leave pickOrderRaw null rather than inventing one from who merely played or scored.
11. Goal-count sanity check: after extracting every goal, the number of goals credited to each side must be consistent with any score you stated for that side (a final score, or an intermediate score mentioned mid-narrative, e.g. "1:1 after half" or "2:2"). If a passage narrates a sequence of events that only yields fewer goals than the score change requires, reread it: a phrase describing one player's own scoring action (e.g. "X untied/tied/leveled the game," "X made it N:M," "X put them ahead") is that player's OWN goal, separate and prior to any following sentence about a different player's own contribution — do not collapse two players' own separate score-changing actions into a single goal/assist pair just because they're described back-to-back in one sentence. Reserve a single goal with an assist for when the narrative describes one continuous play (a pass or setup, then a finish by a different player), not two sequential goals for two different players. Many reports end with an explicit "Goals:" tally listing every scorer with their count (e.g. "Yura Young - 5, Oleg New, Zhenya Def" for one side, a second line for the other) — when present, this tally is the AUTHORITATIVE, primary source for who scored and how many, and takes precedence over the prose: if the prose only narrates some of a player's goals with a specific action and jumps over others (e.g. the score jumps from 5:2 to 7:2 with no description of what happened in between), still emit the additional unnarrated goals for that scorer (with assistRaw null, since no setup was described) so the total matches the tally exactly, rather than only extracting the goals you can individually pin to a described action.

12. Date without a stated year: Gmail's own copy-paste format routinely omits the year entirely — a message header like "Sun, Jun 21, 11:14 AM" or a subject line like "Sunday, June 21," no 4-digit year anywhere in the thread. Do NOT leave date null just because the year specifically is missing — infer it, since this is a real, ongoing recurring league and the report always describes a game already played, never a future one: pick whichever year makes the stated month/day fall on or before today's date (given above), and consistent with any stated day-of-week (e.g. confirm "June 21" actually falls on a Sunday that year, if the text says Sunday). Only leave date null if there isn't enough of a month/day stated anywhere to make any calendar inference at all (e.g. only "last week" with no specific date).

13. Pre-draft balance: a report sometimes separately notes that one or two specific players were handed straight to a side BEFORE the draft/team-picking happened at all, usually to balance a lopsided pool (e.g. "To balance the teams Kimran was given to me and Matthew got Mike, so disclude those from the average draft position," or "X and Y were added pre-draft"). This is a distinct fact from rule 10's normal draft order — these players were never actually drafted in sequence, regardless of where their name happens to sit in the roster listing. When the report states this, extract preDraftBalanceRaw as the raw name(s) it names this way. Being on this list doesn't remove them from homeRosterRaw/awayRosterRaw — they still played, they just weren't a real draft pick. Leave preDraftBalanceRaw null if the report never mentions this.

Respond with ONLY a JSON object matching this exact shape, no other text:
{
  "date": "YYYY-MM-DD or null",
  "league": "saturday" | "sunday" | "unknown",
  "homeRosterRaw": string[],
  "awayRosterRaw": string[],
  "homeTeamLabelRaw": string or null,
  "awayTeamLabelRaw": string or null,
  "homeScore": number or null,
  "awayScore": number or null,
  "goals": [{ "scorerRaw": string, "assistRaw": string or null, "team": "home" | "away" | "unknown" }],
  "mvpRaw": string or null,
  "notableMentions": [{ "playerRaw": string, "quote": string }],
  "pickOrderRaw": (string | string[])[] or null,
  "preDraftBalanceRaw": string[] or null
}

--- THREAD START ---
${threadText}
--- THREAD END ---`;
}
